#!/bin/bash

# Vercel環境変数からconfig.jsを生成するビルドスクリプト
# APIキーは全てVercel環境変数から注入し、ソースコードには含めない

echo "Generating config.js from environment variables..."

[ -z "$GEMINI_API_KEY" ] && echo "Warning: GEMINI_API_KEY is not set." && GEMINI_API_KEY=""
[ -z "$GOOGLE_DRIVE_CLIENT_ID" ] && echo "Warning: GOOGLE_DRIVE_CLIENT_ID is not set." && GOOGLE_DRIVE_CLIENT_ID=""
[ -z "$GOOGLE_DRIVE_API_KEY" ] && echo "Warning: GOOGLE_DRIVE_API_KEY is not set." && GOOGLE_DRIVE_API_KEY=""
[ -z "$GOOGLE_DRIVE_FOLDER_ID" ] && echo "Warning: GOOGLE_DRIVE_FOLDER_ID is not set." && GOOGLE_DRIVE_FOLDER_ID=""

cat > config.js << CONFIGEOF
// Auto-generated from environment variables at build time
// Do not edit this file directly

const API_CONFIG = {
    GEMINI_API_KEY: '${GEMINI_API_KEY}',
    MODEL_NAME: 'gemini-2.5-flash'
};

const DRIVE_CONFIG = {
    CLIENT_ID: '${GOOGLE_DRIVE_CLIENT_ID}',
    API_KEY: '${GOOGLE_DRIVE_API_KEY}',
    TARGET_FOLDER_ID: '${GOOGLE_DRIVE_FOLDER_ID}'
};
CONFIGEOF

echo "config.js generated successfully!"
