#!/bin/bash

# Vercel環境変数からconfig.jsを生成するビルドスクリプト
#
# 必要な環境変数:
#   GEMINI_API_KEY         - Gemini APIキー
#   FIREBASE_API_KEY       - Firebase APIキー
#   FIREBASE_AUTH_DOMAIN   - Firebase Auth ドメイン
#   FIREBASE_PROJECT_ID    - Firebase プロジェクトID

echo "Generating config.js from environment variables..."

[ -z "$GEMINI_API_KEY" ] && echo "Warning: GEMINI_API_KEY is not set."
[ -z "$FIREBASE_API_KEY" ] && echo "Warning: FIREBASE_API_KEY is not set. localStorageモードで動作します。"

cat > config.js << CONFIGEOF
// Auto-generated from environment variables at build time
// Do not edit this file directly

const API_CONFIG = {
    GEMINI_API_KEY: '${GEMINI_API_KEY}',
    MODEL_NAME: 'gemini-2.5-flash'
};

// Firebase設定
const FIREBASE_CONFIG = {
    apiKey: '${FIREBASE_API_KEY}',
    authDomain: '${FIREBASE_AUTH_DOMAIN}',
    projectId: '${FIREBASE_PROJECT_ID}'
};
CONFIGEOF

echo "config.js generated successfully!"
echo "  GEMINI_API_KEY: $([ -n "$GEMINI_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  FIREBASE_API_KEY: $([ -n "$FIREBASE_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  FIREBASE_PROJECT_ID: $([ -n "$FIREBASE_PROJECT_ID" ] && echo 'SET' || echo 'NOT SET')"
