#!/bin/bash

# Vercel環境変数からconfig.jsを生成するビルドスクリプト

echo "Generating config.js from environment variables..."

# GEMINI_API_KEYが設定されているか確認
if [ -z "$GEMINI_API_KEY" ]; then
  echo "Warning: GEMINI_API_KEY is not set. Using empty string."
  GEMINI_API_KEY=""
fi

# config.jsを生成（Google Drive設定も含む）
cat > config.js << 'CONFIGEOF'
// Auto-generated from environment variables at build time
// Do not edit this file directly

const API_CONFIG = {
    // Gemini APIキー（Vercel環境変数から注入）
CONFIGEOF

echo "    GEMINI_API_KEY: '${GEMINI_API_KEY}'," >> config.js

cat >> config.js << 'CONFIGEOF'

    // 使用するモデル
    MODEL_NAME: 'gemini-2.0-flash-exp'
};

// Google Drive API設定
const DRIVE_CONFIG = {
    // OAuth 2.0 クライアントID（Google Cloud Consoleで取得）
    CLIENT_ID: '537186649664-12ft0p2d5a3jkbkpvjoquugfgpoiov86.apps.googleusercontent.com',

    // APIキー（Google Cloud Console > 認証情報 > APIキーを作成）
    API_KEY: 'AIzaSyDen7M5YfihnQYaiHtigRvNewb4f6utUbo',

    // 保存先フォルダID
    TARGET_FOLDER_ID: '1KvbKykAiUK6BKoqsFQQhyRqYQp7NQm77'
};
CONFIGEOF

echo "config.js generated successfully!"
